package com.user.bemp.helper

const val TB_USER = "user"
const val TB_ADMIN = "admin"
const val TB_STRUKTUR_ORGANISASI = "strukturorganisasi"
const val TB_BERITA = "berita"
const val TB_PRESTASI = "prestasi"
const val TB_LOMBA = "lomba"
const val DIVISI = "divisi"
const val ANGGOTA = "anggota"
const val BIO = "bio"
const val KATEGORI = "kategori"
const val ISIBERITA = "isiberita"
const val CAMPAIGN = "campaign"
const val PENDAFTAR = "pendaftar"
const val SHARED_PREFERENCES = "SHARED_PREFERENCES"
const val ID_USER = "ID_USER"
const val NAMA_USER = "NAMA_USER"
const val NIM_USER = "NIM_USER"
const val PRODI_USER = "PRODI_USER"
const val FOTO_PROFIL = "FOTO_PROFIL"
const val SESSION = "SESSION"