package com.admin.bempadmin.helper

const val TB_ADMIN = "admin"
const val TB_USER = "user"
const val TB_STRUKTUR_ORGANISASI = "strukturorganisasi"
const val TB_BERITA = "berita"
const val TB_PRESTASI = "prestasi"
const val TB_LOMBA = "lomba"
const val BIO = "bio"
const val DIVISI = "divisi"
const val ANGGOTA = "anggota"
const val KATEGORI = "kategori"
const val ISIBERITA = "isiberita"
const val CAMPAIGN = "campaign"
const val PENDAFTAR = "pendaftar"
const val SHARED_PREFERENCES = "SHARED_PREFERENCES"
const val ID_ADMIN = "ID_ADMIN"
const val NAMA_ADMIN = "NAMA_ADMIN"
const val STATUS_ADMIN = "STATUS_ADMIN"
const val SESSION = "SESSION"
const val UPDATE = "UPDATE"
const val SUPER_ADMIN = "Super Admin"